# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

jxl_info <- function(filename) {
    .Call(`_jxlr_jxl_info`, filename)
}

R_jxl_get_info <- function(buf) {
    .Call(`_jxlr_jxl_get_info_raw`, buf)
}

R_jxl_decode <- function(buf) {
    .Call(`_jxlr_jxl_decode_raw`, buf)
}

R_jxl_encode <- function(img, quality, effort) {
    .Call(`_jxlr_jxl_encode_raw`, img, quality, effort)
}

R_jxl_decode_anim <- function(buf) {
    .Call(`_jxlr_jxl_decode_anim_raw`, buf)
}

R_jxl_encode_anim <- function(frames, durations, quality, effort, loop_count) {
    .Call(`_jxlr_jxl_encode_anim_raw`, frames, durations, quality, effort, loop_count)
}

